FROM ut_b:latest
#TAG ut_ep:latest
RUN apt-get install -y git cmake build-essential libsdl1.2-dev texinfo gawk chrpath genromfs diffstat
RUN apt-get install -y bc e2fsprogs e2fslibs e2fslibs-dev
RUN apt-get install -y zip lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
RUN apt-get install -y  language-pack-en-base python python-pip
RUN pip install xlrd
