FROM ubuntu:14.04
RUN apt-get update  && apt-get install -y openssh-server
RUN apt-get install -y git cmake build-essential
RUN apt-get install -y vim
ARG user
ARG pw

RUN useradd -m -p $(openssl passwd -crypt $pw) $user
RUN usermod -a -G sudo $user
RUN usermod -s /bin/bash $user

USER $user
RUN which sh
ADD /.bashrc /home/$user/.bashrc

USER root
EXPOSE 22
CMD service ssh start && while true; do sleep 3000; done
